import type {Metadata} from "next";

import React from "react";
import {Inter} from "next/font/google";

import "@/css/globals.css";
import {ThemeProvider} from "next-themes";

import {cn} from "@/lib/utils";
import {SessionWrapper} from "@/components/layout/session-provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background", inter.className)}>
        <SessionWrapper>
          <ThemeProvider
            disableTransitionOnChange
            enableSystem
            attribute="class"
            defaultTheme="light"
          >
            {children}
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
